server:  port: 80spring:  application:    name: springboot-provider-carbon    
  datasource:
    username: hydrocarbon
    password: hydrocarbon
#    url: jdbc:mysql://localhost:3306/t_carbon_test?serverTimezone=UTC
    url: jdbc:mysql://47.110.161.228:13006/dc_dongxi_street?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update  aop:    auto: false
    proxy-target-class: false
    eureka:   client:     register-with-eureka: false     #false表示不向注册中心注册自己。    service-url: #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      defaultZone: http://eureka7001.com:7001/eureka/feign:  hystrix:    enabled: false    hystrix:  command:    default:      execution:        isolation:          thread:            timeoutInMilliseconds: 5000  #熔断超时时间ribbon:  ReadTimeout: 60000  #请求处理的超时时间  ConnectTimeout: 60000 #请求连接超时时间  MaxAutoRetries: 0 #对当前实例的重试次数  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1    